# Generated by Django 2.1.3 on 2018-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20181103_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
